# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_wrangling_agent
# Time Created: 2025-04-15 21:38:04

def data_wrangler(data_list):
    import pandas as pd
    import numpy as np
    '''
    Wrangle the data provided in data_list.
    
    data_list: A list of one or more pandas data frames containing the raw data to be wrangled.
    '''


    # If input is not a list, convert it to a list for uniform handling
    if not isinstance(data_list, list):
        data_list = [data_list]
    
    # Since the user provided only one dataset ("main"), use the first one.
    df = data_list[0].copy()
    
    # The user wants to join the "price" and "bike_model" columns with the word "duпа" 
    # between (where "duпа" is the word "dupa" written in Cyrillic letters).
    # price is int, so convert it to string for concatenation.
    
    # Create a new column (could replace an existing one or add new column if needed). 
    # The instruction is to "połącz kolumny" which means "concatenate/merge columns"
    # Put the concatenated result back - likely replacing 'bike_model' or create a new col.
    
    # We'll replace bike_model with the concatenation according to user instruction.
    
    # Unicode string for "duпа": Cyrillic "д" (U+0434), "у" (U+0443), "п" (U+043F), "а" (U+0430)
    separator = 'дупа'
    
    # Concatenate as string: str(price) + separator + bike_model
    df['bike_model'] = df['price'].astype(str) + separator + df['bike_model']
    
    # Return the modified dataframe
    return df