# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 17:42:04

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.express as px
    import plotly.io as pio





    # Calculate the distribution of classifications by research topics
    classification_distribution = data_raw.groupby(['Badanie', 'Klasyfikacja']).size().reset_index(name='Counts')
    total_counts = classification_distribution.groupby('Badanie')['Counts'].transform('sum')
    classification_distribution['Percentage'] = classification_distribution['Counts'] / total_counts * 100

    # Create a stacked bar chart
    fig = px.bar(classification_distribution, 
                  x='Percentage', 
                  y='Badanie', 
                  color='Klasyfikacja', 
                  color_discrete_sequence=['yellow', 'red', 'green'], 
                  title="Distribution of Classifications by Research Topics",
                  labels={"Percentage": "Percentage of Classifications", "Badanie": "Research Topics"},
                  text='Counts')

    # Update layout for better readability
    fig.update_layout(barmode='stack', xaxis_title='Percentage of Classifications', yaxis_title='Research Topics')

    # Convert figure to JSON
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict