# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-26 15:44:14

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.express as px
    import plotly.graph_objects as go
    import plotly.io as pio






    # Assume data_raw is a pandas DataFrame matching Dataset_0
    df = data_raw.copy()

    # Create horizontal stacked bar chart
    fig = px.bar(
        df,
        x="Percentage",
        y="Badanie",
        color="Klasyfikacja",
        orientation="h",
        barmode="stack",
        color_discrete_sequence=["#FFD700", "red", "green"],
        title="Skumulowany wykres słupkowy procentowego udziału klasyfikacji w badaniach",
        template="plotly_white"
    )

    # Update axis and legend titles
    fig.update_layout(
        xaxis_title="Procentowy udział (%)",
        yaxis_title="Badanie",
        legend_title="Klasyfikacja"
    )

    # Convert figure to JSON dict
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict