# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_wrangling_agent
# Time Created: 2025-04-16 21:40:39

def data_wrangler(data_list):
    import pandas as pd
    import numpy as np
    '''
    Wrangle the data provided in data_list.
    
    data_list: A list of one or more pandas data frames containing the raw data to be wrangled.
    '''


    # Ensure that the input is a list of DataFrames
    if not isinstance(data_list, list):
        data_list = [data_list]
    
    # Since user instruction refers to "poprzedniej tabelii z datą" (previous table with date)
    # and dataset summary shows one dataframe named 'main', we take the first DataFrame.
    df = data_list[0].copy()
    
    # The user wants to "change the date one year forward".
    # The relevant date column is 'Czas rozpoczęcia' which looks like:
    # "2024-10-09 09:13:22" - a datetime string.
    # We'll convert this column to datetime type if not already and add 1 year.

    # Convert to datetime, errors='coerce' to handle any invalid parsing safely
    df['Czas rozpoczęcia'] = pd.to_datetime(df['Czas rozpoczęcia'], errors='coerce')
    
    # Add one year to the datetime.
    # Adding one year can be done using DateOffset(years=1)
    df['Czas rozpoczęcia'] = df['Czas rozpoczęcia'] + pd.DateOffset(years=1)

    # Return the wrangled DataFrame
    return df