Ogólny opis danych:
- Zbiór danych zawiera badania efektywnoiści agentów ubezpieczeniowych w firmie. 
- Dostępne kolumny: { df.columns.tolist() }

Analiza danych:
Page 1:
    - Title: "MULTI OBSERVATION STUDY DLA SPECJALISTÓW I UNDERWRITERÓW"
    - Charts: "Wykres kołowy przedstawiający procentowy udział wartości w kolumnie "Klasyfikacja"."
    - Description: "Marnotrawienia czasu. VA to wartość dodana, NVA-K to marnotrastwo koniecznie, NVA-O marnotrastwo oczywiste. Weź pod uwagę komentarze z kolumny Komentarz"
Page 2:
    - Title: "MULTI OBSERVATION STUDY PODSUMOWANIE MS-A"
    - Charts: |
        "Skumulowany wykres słupkowy poziomy (stacked bar chart).
        Wykres na osi y prezentuje wartości z kolumny "Badanie". Na osi x prezentuje procentowo wartości z kolumny "Klasyfikacja".
        Przedstawia on udział trzech Klasyfikacji "Klasyfikacja" (oznaczonych kolorami: żółty, czerwony i zielony) w łącznej wartości 100% dla różnych Badań (kolumna "Badanie"). 
    - Description: "Marnotrawienia czasu. VA to wartość dodana, NVA-K to marnotrastwo koniecznie, NVA-O marnotrastwo oczywiste. Weź pod uwagę komentarze z kolumny Komentarz"
Page 3:
    - Title: "MULTI OBSERVATION STUDY PODSUMOWANIE MS-A"
    - Charts: "Brak wykresu"
    - Description: "Przedstaw tabelę z TOP 3 wartości "Podczynność" dla "Klasyfikacja"""
