Ogólny opis danych:
- Zbiór danych zawiera informacje o sprzedaży rowerów.

Strona 1:
  - Tytuł: "Podstawowa analiza sprzedaży"
  - Wykresy:
    - "Pokaż całkowitą sprzedaż w formie wykresu słupkowego"
  - Opis: "Przedstaw podstawową analizę danych sprzedażowych" 